# Generated by Django 6.0.5 on 2026-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_request', models.TextField()),
                ('intent', models.CharField(choices=[('send_money', 'Send Money'), ('hire_service', 'Hire Service'), ('verify_document', 'Verify Document'), ('airport_transfer', 'Airport Transfer'), ('check_status', 'Check Status')], max_length=50)),
                ('extracted_entities', models.JSONField()),
                ('risk_score', models.IntegerField(default=0)),
                ('employee_assignment', models.CharField(max_length=100)),
                ('generated_steps', models.JSONField()),
                ('whatsapp_message', models.TextField()),
                ('email_message', models.TextField()),
                ('sms_message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
