# Generated by Django 6.0.5 on 2026-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auditlog_statushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='customer_request',
            field=models.TextField(default='No request provided'),
        ),
        migrations.AlterField(
            model_name='task',
            name='email_message',
            field=models.TextField(default='Your request is under review'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee_assignment',
            field=models.CharField(default='Support Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='generated_steps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='intent',
            field=models.CharField(choices=[('send_money', 'Send Money'), ('hire_service', 'Hire Service'), ('verify_document', 'Verify Document'), ('airport_transfer', 'Airport Transfer'), ('check_status', 'Check Status')], default='check_status', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='sms_message',
            field=models.TextField(default='Request received'),
        ),
        migrations.AlterField(
            model_name='task',
            name='whatsapp_message',
            field=models.TextField(default='Request received'),
        ),
    ]
